[package]
name = "email-server-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gotham = "0.7.1"
lettre = "0.10.1"
dotenv = "0.15.0"
serde = "1.0.144"
futures = "0.3.24"
